name: Test
on:
  push:
  workflow_dispatch:
env:
  CI: true
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: npm ci
        run: npm ci

      - name: run lint
        run: npm run lint

      - name: install Playwright
        run: npx playwright install --with-deps > /dev/null

      - name: run features
        run: npm run test

      # Optionally add a couple of fields such as the git hash and link to the build
      - name: Prepare resources
        run: |
          npx testmo automation:resources:add-field --name git --type string \
            --value ${GITHUB_SHA:0:7} --resources resources.json
          RUN_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          npx testmo automation:resources:add-link --name build \
            --url $RUN_URL --resources resources.json

      # Run automated tests and report results to Testmo
      - name: Run tests
        run: |
          npx testmo automation:run:submit \
            --instance "$TESTMO_URL" \
            --project-id 1 \
            --name "Test run" \
            --source "frontend" \
            --resources resources.json \
            --results artifacts/*.xml \
            -- npm run test
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_SECRET }}

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: reports/allure-results
          keep_reports: 25
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: Post the link to the report
        env:
          RUN_NUMBER: ${{ github.run_number }}
          run: echo ::set-env name=REPORT_VERSION::$(($RUN_NUMBER+1))
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.PERSONAL_TOKEN}}
          context: 'Allure report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          target_url: https://vdencow.github.io/testallure/$REPORT_VERSION
